### ISSUE TITLE
Expose makePng_() as public

### ISSUE THREAD

**Issue by keesey** [imaya/CanvasTool.PngEncoder#1]
I'd like to suggest that the `makePng_()` function be exposed as a public function (not renamed when minified). For my purposes an array of numbers is much more useful than an encoded string (although an `ArrayBuffer` or `Uint8Array` would be even more useful) .

**Comment by imaya** [comment]
The makePng_() function was renamed to the convertToArray() function, and changed to public function. This function returns Array.<number > now, and when Uint8Array can be used in the future, it is likely to be changed to return it.

**Comment by keesey** [comment]
That was fast! Just checked and it works great. Thanks!
